///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryItemModel {
/*
{
  "_id": "59f1e49a9bfd8f3bd030eed7",
  "title": "轻薄本",
  "status": 1,
  "pic": "public\\upload\\HYWKHxrKgE9O6zKajRTmb50B.png",
  "pid": "59f1e1ada1da8b15d42234e9",
  "sort": 100,
  "is_best": 1,
  "go_product": 1,
  "product_id": "59f1e49a9bfd8f3bd030eed7"
} 
*/

  String? sId;
  String? title;
  int? status;
  String? pic;
  String? pid;
  int? sort;//object类
  int? isBest;
  int? goProduct;
  String? productId;

  CategoryItemModel({
    this.sId,
    this.title,
    this.status,
    this.pic,
    this.pid,
    this.sort,
    this.isBest,
    this.goProduct,
    this.productId,
  });
  CategoryItemModel.fromJson(Map<String, dynamic> json) {
    sId = json['_id']?.toString();
    title = json['title']?.toString();
    status = json['status']?.toInt();
    pic = json['pic']?.toString();
    pid = json['pid']?.toString();
    sort = json['sort'] != null ? int.parse(json['sort'].toString()) : null;
    isBest = json['is_best']?.toInt();
    goProduct = json['go_product']?.toInt();
    productId = json['product_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = sId;
    data['title'] = title;
    data['status'] = status;
    data['pic'] = pic;
    data['pid'] = pid;
    data['sort'] = sort;
    data['is_best'] = isBest;
    data['go_product'] = goProduct;
    data['product_id'] = productId;
    return data;
  }
}

class CategoryModel {
/*
{
  "result": [
    {
      "_id": "59f1e49a9bfd8f3bd030eed7",
      "title": "轻薄本",
      "status": 1,
      "pic": "public\\upload\\HYWKHxrKgE9O6zKajRTmb50B.png",
      "pid": "59f1e1ada1da8b15d42234e9",
      "sort": 100,
      "is_best": 1,
      "go_product": 1,
      "product_id": "59f1e49a9bfd8f3bd030eed7"
    }
  ]
} 
*/

  List<CategoryItemModel?>? result;

  CategoryModel({
    this.result,
  });
  CategoryModel.fromJson(Map<String, dynamic> json) {
  if (json['result'] != null) {
  final v = json['result'];
  final arr0 = <CategoryItemModel>[];
  v.forEach((v) {
  arr0.add(CategoryItemModel.fromJson(v));
  });
    result = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      final v = result;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['result'] = arr0;
    }
    return data;
  }
}
