///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PlistItemModel {
/*
{
  "_id": "6332bc60a3a7080ac06eaee8",
  "title": "小米12s",
  "cid": "59f1e4919bfd8f3bd030eed6",
  "price": 2999,
  "pic": "public\\upload\\5xyr9OTSK1pwJ5ng7YgpKOkd.png",
  "sub_title": "下单立减100",
  "s_pic": "public\\upload\\5xyr9OTSK1pwJ5ng7YgpKOkd.png_200x200.png"
} 
*/

  String? sId;
  String? title;
  String? cid;
  int? price;
  String? pic;
  String? subTitle;
  String? sPic;

  PlistItemModel({
    this.sId,
    this.title,
    this.cid,
    this.price,
    this.pic,
    this.subTitle,
    this.sPic,
  });
  PlistItemModel.fromJson(Map<String, dynamic> json) {
    sId = json['_id']?.toString();
    title = json['title']?.toString();
    cid = json['cid']?.toString();
    price = json['price']?.toInt();
    pic = json['pic']?.toString();
    subTitle = json['sub_title']?.toString();
    sPic = json['s_pic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = sId;
    data['title'] = title;
    data['cid'] = cid;
    data['price'] = price;
    data['pic'] = pic;
    data['sub_title'] = subTitle;
    data['s_pic'] = sPic;
    return data;
  }
}

class PlistModel {
/*
{
  "result": [
    {
      "_id": "6332bc60a3a7080ac06eaee8",
      "title": "小米12s",
      "cid": "59f1e4919bfd8f3bd030eed6",
      "price": 2999,
      "pic": "public\\upload\\5xyr9OTSK1pwJ5ng7YgpKOkd.png",
      "sub_title": "下单立减100",
      "s_pic": "public\\upload\\5xyr9OTSK1pwJ5ng7YgpKOkd.png_200x200.png"
    }
  ]
} 
*/

  List<PlistItemModel?>? result;

  PlistModel({
    this.result,
  });
  PlistModel.fromJson(Map<String, dynamic> json) {
    if (json['result'] != null) {
      final v = json['result'];
      final arr0 = <PlistItemModel>[];
      v.forEach((v) {
        arr0.add(PlistItemModel.fromJson(v));
      });
      result = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      final v = result;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['result'] = arr0;
    }
    return data;
  }
}
